### PR TITLE
test case for person(staff and fellow)

### PR DESCRIPTION
**Pull request by AndersonMasese**
test case for the person

### CODE REVIEW

**Review by morriskimani — COMMENTED** [review]
Why was this PR merged into master? Most importantly, why was it merged before being reviewed?

**Comment by AndersonMasese** [comment]
After the error with my git, I realized that it is not allowed to clone a
branch of a repository, in my case branch development. I found that the one
that we had cloned did not have any files in it since all of them were in
the other branch,...I found myself weighing between losing all of my commit
history and merging the branches. I chose the former since I can continue
my work on a different branch and still edit files in master after review
since they are not very many inside there...

**Comment by morriskimani** [comment]
I understand. However that was not the wisest thing to do. After cloning a repository, what you see locally is the default branch (in your case `master`). What you should have done was simply to `checkout` to your `development` branch.

**Comment by AndersonMasese** [comment]
Oh yea I get,it's just today that I fully grasped the magic of
branching.Now I won't be making such mistakes

**Pull request merged**
